### ISSUE TITLE
Folder structuur

### ISSUE THREAD

**Issue by BerendWeij** [jscotty/MytheCortes#1]
``` c
Buttons     
Enemy       
Player      
data        
health-expbars 
```

Bestand: https://github.com/jscotty/MytheCortes/tree/master/Assets/Scripts

Groepeer je code volgens een duidelijke onderverdeling.
Bijvoorbeeld:

Debug/
Gameplay/
    Actors/
    Items/
Framework/
GUI/
...

Ook hierbinnen kun je nog specifieke folders aanmaken. Probeer te voorkomen dat je in een folder heel veel script bestanden hebt staan.

**Comment by jscotty** [comment]
https://github.com/jscotty/MytheCortes/tree/master/Assets/Scripts

Ik doe mijn best zo goed mogelijk structuur te maken, ik vind het wel lastig om goede benamingen te vinden, ook heb ik swan erop gewezen zijn scripts goed in mappen te uploaden
