### ISSUE TITLE
tijdelijke class?

### ISSUE THREAD

**Issue by erwinhenraat** [jscotty/MytheCortes#12]
Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/CubeColor.cs

Deze class lijkt me niet erg duurzaam. Is dit een tijdelijke class? Zet hem dan even in een temp package oid.

Of bedenk hoe je deze class ook herbruikbaar kunt maken voor andere missions

**Comment by jscotty** [comment]
aangegeven bij swan
