### ISSUE TITLE
Encapsulation

### ISSUE THREAD

**Issue by erwinhenraat** [jscotty/MytheCortes#13]
``` c
public float x,y; 
```

Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Player/PlayerController.cs

Zorg dat deze variabelen niet zomaar benaderbaar zijn. Gebruik getters en of setters.

**Comment by jscotty** [comment]
oops foutje, heb het over het hoofd gezien, had dit om te testen in het begin gedaan
