### ISSUE TITLE
scope aangeven

### ISSUE THREAD

**Issue by erwinhenraat** [jscotty/MytheCortes#15]
``` c
InteractButtonText _btnText;
    SwordAnim _swordAnim;
    TalkScript _talkScript;
    Joystick _joystick;
    CharacterData _playerData;
    bool _talk;
    float _count;
    float _textIndex; 
```

Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Player/PlayerTrigger.cs

Het is netjes om voor al je variabelen even de scope aan te geven. Niet alleen in deze class!
geef dus aan of ze private, public protected of internal zijn.

**Comment by jscotty** [comment]
dit doe ik voor mijzelf om aan tegeven welke private variable een getter and setter heeft/ serializeble field is. ik vind het daardoor prettig om het zo te schrijven
