### ISSUE TITLE
Opruimen

### ISSUE THREAD

**Issue by RichardRam87** [jscotty/MytheCortes#18]
``` c
public class ButtonScript : MonoBehaviour {


} 
```

Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Buttons/ButtonScript.cs

Laat lege, oude Classes en/of functies niet staan maar verwijder ze uit je repos als je ze niet meer gaat gebruiken.

**Comment by jscotty** [comment]
is verwijdert
