### ISSUE TITLE
Gebruik enums

### ISSUE THREAD

**Issue by RichardRam87** [jscotty/MytheCortes#19]
``` c
public void OnDown(string button){
        if (button == "RIGHT") {
            _xAxis = 1f;
            _yAxis = 0f;
        } else if (button == "LEFT") {
            _xAxis = -1f;
            _yAxis = 0;
        } else if (button == "UP") {
            _xAxis = 0;
            _yAxis = 1f;
        } else if (button == "DOWN") {
            _xAxis = 0;
            _yAxis = -1f;
        } else if (button == "INTERACT") {
            _interact = true;
        } 
```

Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Buttons/Joystick.cs

Gebruik enums voor type opsomming. Dit voorkomt de kans op foutjes in samenwerking. Probeer het gebruik van inline strings te minimaliseren.

**Comment by jscotty** [comment]
https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Buttons/Joystick.cs

ik hoop dat dit goed is.

**Comment by RichardRam87** [comment]
Ja, vervolgens dit ook gebruiken in je OnDown functie.
Waarom geeft je ReverseDirection() een Direction terug, de functie doet zelf niets met deze variabelen?

**Comment by jscotty** [comment]
Dat kwam vanwegen een tutorial die ik volgde om meer te weten te komen over enums, en toen het werkte heb ik het niet meer aangepast
