### ISSUE TITLE
Houdt interface logica en game logica gescheiden

### ISSUE THREAD

**Issue by BerendWeij** [jscotty/MytheCortes#2]
``` c
if (button == "RIGHT") {
            playerController.x = 1f;
            playerController.y = 0f;
        } else if (button == "LEFT") {
            playerController.x = -1f;
            playerController.y = 0;
        } else if (button == "UP") {
            playerController.x = 0;
            playerController.y = 1f;
        } else if (button == "DOWN") {
            playerController.x = 0;
            playerController.y = -1f;
        } else if (button == "INTERACT") {
            playerController.attack = true;
        } 
```

Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Buttons/ButtonScript.cs

Houdt interface logica en game logica gescheiden.

Hiermee bedoelen we:
interface logica: alle logica die je nodig hebt om op interface acties te reageren (klikken, swipen, etc.).

game logica: de logica die je hebt om je game te laten draaien. Bijvoorbeeld je speler opzij laten kijken.

Probeer dit ook goed te verdelen in je Classes.

Stel we besturen een speler met een 'onScreen' joystick.
Je kan dan een component schrijven JoystickController. Hier stop je alle logica in om te kijken of en welke knoppen er worden ingedrukt. Vervolgens schrijf je ook een andere component voor je speler met functies en getters en setters. Via deze functies, getters en setters kun je de speler vragen bepaalde dingen te doen.

Stel de JoystickController ziet dat je de joystick naar beneden beweegt, dan kan je controller script de player component aanspreken en een functie aanroepen. Je speler Class bepaald vervolgens wat er allemaal gebeurd.

Dit maakt je code een stuk vrijer. Je kunt zo ook bepaalde logica veel makkelijker van verschillende plekken aanroepen.

**Comment by jscotty** [comment]
https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Buttons/Joystick.cs

Ik heb nu getters and setters gemaakt waarvan ik nu uit de controller class de xAxis/yAxis van de joystick uit opvraag.
