### ISSUE TITLE
Consistent taalgebruik

### ISSUE THREAD

**Issue by RichardRam87** [jscotty/MytheCortes#20]
``` c
// berekent het verschil tussen player en positie 
```

Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Camera/CameraMovement.cs

Wees consistent in je taalgebruik; van code & van comments. Engels dus.

**Comment by jscotty** [comment]
oopsie was nog een oude comment, ik ga het aanpassen
