### ISSUE TITLE
Dynamische code

### ISSUE THREAD

**Issue by RichardRam87** [jscotty/MytheCortes#21]
``` c
if(_playerData.quest == 1 && _playerData.questProgress < 100){
                _playerData.questProgress = 100;
            } 
```

Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Enemy/DummyBehaviour.cs

Ik weet niet hoeveel quests je gaat hebben, maar dit gaat zo net dynamisch werken en is dus niet handig!
Daarnaast vraag ik me af wat een damaging boolean te maken heeft met de questprogressie? Zijn dit niet twee verschillende verantwoordelijkekheden in één class?

**Comment by jscotty** [comment]
https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Quests/QuestState.cs

Ik heb het aangepast door een aparte classe te maken waarin ik methodes schrijf zoals het eindigen van een quest, en het update van de quest progressions etc
