### ISSUE TITLE
Let op je updates

### ISSUE THREAD

**Issue by RichardRam87** [jscotty/MytheCortes#22]
``` c
void Update(){
        _attack = _playerController.GetAttack ();
        if (_hit && _attack) {
            _dummy.SetDamaging(true);
        } else {
            _dummy.SetDamaging(false);

        } 
```

Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Enemy/HitDetection.cs

Let op dat je geen performance verspilt door updates te blijven doen met berekeningen als dit niet meer nodig is.

In combinatie met je Dummyclass kan dit efficienter door één specifieke functie aan te roepen. DoDamage(int amount) bijvoorbeeld;
Dit scheelt je constant checken in de Dummybehaviour class of een boolean true of false is.

**Comment by jscotty** [comment]
https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Enemy/HitDetection.cs

opgelost, Had het zo gedaan om te testen, ik heb het nu met het sword object gedaan aangezien die alleen actief is bij het aanvallen
