### ISSUE TITLE
Gebruik enums

### ISSUE THREAD

**Issue by RichardRam87** [jscotty/MytheCortes#23]
``` c
/// <summary>
    /// The character sprites.
    /// 0 = is down
    /// 1 = up
    /// 2 = left and right
    /// </summary> 
```

Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Player/PlayerController.cs

Het is handiger om voor dit soort opsomming enums te gebruiken. Je maakt het al leesbaar door comments te plaatsen, maar dit kan beter. Is er een specifieke rede waarom jullie ervoor kiezen om ints te gebruiken?

**Comment by jscotty** [comment]
ik ben nog niet zo bekend met enums, maar bedankt heb het meteen toegevoegt en zal het zeker vaker proberen te gebruiken,

En ik gebruik ints als ik geen komma getal hoef te hebben, dat vind ik dan duidelijker voor me zelf.
