### ISSUE TITLE
Overbodig

### ISSUE THREAD

**Issue by RichardRam87** [jscotty/MytheCortes#24]
``` c
public Text txt;
    string _message;
    float seconds = 0.01f;
    Story tutStory;
    string _npc;
    TalkScript talk;
    CharacterData _playerData;
    PlayerController _playerController;
    int _quest, _questProgress, _questDone;
    Joystick joystick; 
```

Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Talk/AutoType.cs

Zijn al deze referenties nodig?
Deze class is/moet alleen verantwoordelijk zijn voor het typen van text (toch?) .

**Comment by jscotty** [comment]
https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Talk/QuestTalk.cs

Klopt helemaal, heb het aangepast en gesplitst
