### ISSUE TITLE
Overbodig

### ISSUE THREAD

**Issue by RichardRam87** [jscotty/MytheCortes#25]
``` c
public class CharacterData : MonoBehaviour { 
```

Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/data/CharacterData.cs

Waneer je een pure C# functie hebt, is het niet noodzakelijk om over te ervan van Monobehaviour.
In dat geval kun je een class niet meer Instantiaten, maar moet je deze aanmaken via zijn constructor.

**Comment by jscotty** [comment]
oops
