### ISSUE TITLE
Naamgeving

### ISSUE THREAD

**Issue by RichardRam87** [jscotty/MytheCortes#26]
``` c
HitPointsScript 
```

Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/health-expbars/HitPointsScript.cs

Gebruik niet het woord "Script" in je classNaam. Het is toch al duidelijk dat we het in dit geval over een script hebben.

**Comment by jscotty** [comment]
Ik had dit gedaan omdat ik dan aangeef dat het alles temaken heeft met de HitPoints, dus de bar en handelingen en niet alleen hoeveel levens een character heeft
