### ISSUE TITLE
DRY - Do not repeat yourself

### ISSUE THREAD

**Issue by BerendWeij** [jscotty/MytheCortes#3]
``` c
if (damaging) {
            GetComponent<SpriteRenderer>().color = Color.yellow;
        } else {
            GetComponent<SpriteRenderer>().color = Color.red;
        } 
```

Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Enemy/DummyBehaviour.cs

Probeer je functies zo te schrijven zodat je geen overlap hebt in regels code. Dit noem je DRY coderen. Do Not Repeat Yourself. Als je wel jezelf herhaalt qua code dan wordt je code niet alleen langer, maar je moet ook je code op meer plekken wijzigen als je toch iets moet veranderen aan de logica.

GetComponent zou je buiten de if kunnen doen.
Sowieso is het niet netjes om dit steeds in een update te doen.

**Comment by jscotty** [comment]
https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Enemy/DummyBehaviour.cs

Heb dit opgelost , ik ben nog beetje nieuw met unity en moet wel erg wennen, maar doe mijn best, en had dit eigenlijk wel moeten zien..
