### ISSUE TITLE
Gebruik duidelijke namen - single responsibility principle

### ISSUE THREAD

**Issue by BerendWeij** [jscotty/MytheCortes#4]
``` c
public class AnimatorScript : MonoBehaviour { 
```

Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Player/AnimatorScript.cs

Class names moeten duidelijk zijn.
Verder moeten binnen OOP class names altijd een zelfstandig naamwoord zijn (kat, neus, boom, auto, etc.).

Wat betekent de naam AnimatorScript?
Wat doet het? Sta goed stil bij de naam.

**Comment by jscotty** [comment]
was inderdaad geen goede benaming, ik hoop dat SwordAnim beter is, aangezien het gaat om de animatie van het zwaard

https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Player/SwordAnim.cs
