### ISSUE TITLE
Maak gebruik van constants

### ISSUE THREAD

**Issue by BerendWeij** [jscotty/MytheCortes#5]
``` c
player = GameObject.FindGameObjectWithTag ("Player"); 
```

Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Player/AnimatorScript.cs

Probeer niet 'inline' strings te gebruiken zoals player = GameObject.FindGameObjectWithTag ("Player");. Je maakt snel typfouten. Voor andere developers is het ook moeilijk om de 'strings' te vinden in je code. Probeer daarom altijd met variabelen te werken waar de 'strings' in zijn opgeslagen en plaats deze variabelen bovenin je Class. 
In het geval van de namen van je Scenes en tags is het erg handig om een 'constants' Class te maken met alleen maar constant variables. Hierin zet je alle namen. Vervolgens kun je verwijzen naar deze variabelen door bijvoorbeeld gebruik te maken van Application.LoadLevel(Scenes.GAME). Een voorbeeld van zo'n Class kun je hier vinden: http://unity3d.com/learn/tutorials/projects/stealth/tag-management . In dit artikel laten ze de Class Monobehaviour extenden. Maar dit is niet nodig.

**Comment by jscotty** [comment]
https://github.com/jscotty/MytheCortes/tree/master/Assets/Scripts/References

Ik heb hier een map met de referencies van mijn Tags en names die constant moeten zijn , Ook heb ik nu gebruik gemaakt van read-only, dit zijn run-time variables dus die worden dan alleen geladen als ze aangeroepen worden, dit heb ik zo gedaan vanwegen een string array
