### ISSUE TITLE
GetComponent is vrij zwaar

### ISSUE THREAD

**Issue by BerendWeij** [jscotty/MytheCortes#6]
``` c
attack = player.GetComponent<PlayerController> ().attack;
        gameObject.GetComponent<AttackScript> ().attacking = attack; 
```

Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Player/AnimatorScript.cs

Probeer niet de hele tijd GetComponent te doen. Je kunt dit ook in een Start of Awake opslaan in een variable. Dan hoef je dit vervolgens niet steeds te doen.

**Comment by jscotty** [comment]
Ik had niet goed gekeken en dacht dat als ik het in de start functie aanriep dat het dan maar 1x zal lezen en dus niet zal kunnen updaten... maar dat was niet zo slim van mij
