### ISSUE TITLE
Let op encapsulation api

### ISSUE THREAD

**Issue by BerendWeij** [jscotty/MytheCortes#7]
``` c
player.GetComponent<PlayerController> ().attack = attack;
        player.GetComponent<PlayerController> ().move = move; 
```

Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/Player/AnimatorScript.cs

AnimatorScript.cs weet teveel van de wereld om zich heen. Hij spreekt hard properties aan van andere Classes. Dit mag niet. Je doorbreekt zo de regel van encapsulation: elk object heeft een eigen verantwoordelijkheid en denkt alleen voor zichzelf.

Maak gebruik van functies en getters en setters. Hiermee blijft het aanpassen van data de verantwoordelijkheid van de Class waar de functies en getters en setters in zijn geschreven. Deze Class heeft hierdoor een zogenoemde API.

**Comment by jscotty** [comment]
bedankt voor de issue heb het aangepast
