### ISSUE TITLE
Gebruik duidelijke namen - single responsibility principle

### ISSUE THREAD

**Issue by BerendWeij** [jscotty/MytheCortes#8]
``` c
public class ExpBarScript : MonoBehaviour { 
```

Bestand: https://github.com/jscotty/MytheCortes/blob/master/Assets/Scripts/health-expbars/ExpBarScript.cs

Class names moeten duidelijk zijn.
Verder moeten binnen OOP class names altijd een zelfstandig naamwoord zijn (kat, neus, boom, auto, etc.).

Gebruik sowieso niet het woord Script in je naam.

**Comment by jscotty** [comment]
Script is verwijderd
