### ISSUE TITLE
Te veel classes in de root

### ISSUE THREAD

**Issue by erwinhenraat** [jscotty/MytheCortes#9]
Bestand: https://github.com/jscotty/MytheCortes/tree/master/Assets/Scripts

Maak packages aan om je classes te organiseren. Het is nu erg onduidelijk om structuur te herkennen. Dit is onoverzichtelijk.

**Comment by jscotty** [comment]
was vergeten te pushen, hier had ik namenlijk al aan gewerkt, maar toen was er een push/pull fail en kreeg ik weer alles door elkaar, ook heb ik aan swan aangegeven dat hij zijn scripts in folders moet doen.
